[package]
name = "rustymaze"
version = "0.1.0"
authors = ["Daniel Heath <daniel@heath.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "> 0.23.0"
rand = "> 0.0.1"